"""Initial commit

Revision ID: 352b543ad3a6
Revises: 
Create Date: 2025-03-03 23:53:50.315267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '352b543ad3a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['title'])
        batch_op.drop_column('state')
        batch_op.drop_column('rating')

    with op.batch_alter_table('user_library', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_library', schema=None) as batch_op:
        batch_op.drop_column('state')
        batch_op.drop_column('rating')

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('state', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
